baseURL = "https://www.chenyifeng.com/"
locale = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Voice"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 5
  [[menu.main]]
    name = "逸峰闲话"
    url = "/yifeng-talks/"
    weight = 8
  [[menu.main]]
    name = "五千年架构师"
    url = "/5000-architect/"
    weight = 10
  [[menu.main]]
    name = "业主维权"
    url = "/property-rights/"
    weight = 20
  [[menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 30
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  series = "series"

[params]
  author = "陈逸峰"
  DateFormat = "2006年1月2日"
  disableSpecial1stPost = true
  mainSections = ["5000-architect", "property-rights", "yifeng-talks"]
  ShowReadingTime = true
  ShowWordCount = true
  ShowBreadCrumbs = true
  [params.fuseOpts]
    keys = ["title"]

  # 开启主页名片模式
  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Hi, this is Chen Yifeng. I blog to think about interesting things."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
    [markup.goldmark.extensions]
      typographer = false

[pagination]
  pagerSize = 8
